"""
Django settings for ecomstore project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGIN_REDIRECT_URL = '/accounts/my_account/' 
AUTH_PROFILE_MODULE = 'accounts.userprofile' 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't6cpfhw54*q70ex1x)20!90a9aol%zyuv0nrg4=5w($ic45!t@'

# Change to true before deploying into production
ENABLE_SSL = False

# SECURITY WARNING: don't run with debug turned on in production!
# Basically the host header (or X-Forwarded-Host if USE_X_FORWARDED_HOST is enabled) should match one of the values in ALLOWED_HOSTS.
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'mywebsite.com']
DEBUG=True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_db_logger',
    'catalog',
    'utils',
    'cart',
    'django.contrib.flatpages',# This is added in order to add static pages in Django
    'django.contrib.sites',# This is added in order to add static pages in Django
    'checkout',
    'constance.backends.database',
    'constance',
    'bootstrap3',
    'accounts',
]
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_CONFIG = {
    'AUTHNET_POST_URL': ('test.authorize.net', ""),
    'AUTHNET_POST_PATH':('/gateway/transact.dll',''),
    'AUTHNET_LOGIN':('6wC7Ww5rT4',''),
    'AUTHNET_KEY':('33ye388Ju8cGVF3u',''),
    
}

SITE_ID = 1 # This is the ID of the site record created in admin

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware', # Added from Book
    'SSLMiddleware.SSLRedirect',
]

ROOT_URLCONF = 'ecomstore.urls'

CURRENT_PATH = os.path.abspath(os.path.dirname(__file__).decode('utf-8')).replace('\\', '/') 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(CURRENT_PATH, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',# This passes the static path in the template
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.i18n',  # This is extra from book and not by default
                'django.core.context_processors.media', # This is extra from book and not by default. This passed MEDIA_URL path to templte
                'utils.context_processors.ecomstore', # This is developed on this project from utils app
            ],
        },
    },
]

WSGI_APPLICATION = 'ecomstore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

MEDIA_URL = '/static/images/'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'ecomstore',
        'USER':'django_test',
        'PASSWORD':'django',
        'HOST':'localhost',
        'PORT':'5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_NAME = 'Modern Musician'
META_KEYWORDS = 'Music, instruments, music accessories, musician supplies'
META_DESCRIPTION = 'Modern Musician is an online supplier of instruments,sheet music, and other accessories for musicians' 

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Paypal url
paypal_sandbox = True
paypal_sandbox = "https://api.sandbox.paypal.com/v1"
paypal_live = "https://api.paypal.com/v1" 
client_id = "ARJpqrOtO1sax98KUUb6pGJjuXociFWtN8WSBdPyQmxnslA-86xVwyUCiowS9ZY0trBH2MikwxNE3dLQ"
client_secret = "EPIyljPmT5x502wu0J5qsl4julEBzRSonLhX3i-Tc8m14SI6bQX8uJsBuY4-Uu1-bfx4-QMs47_kQm9k"