# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=200, verbose_name='Payment ID')),
                ('payment_token', models.CharField(max_length=200, verbose_name='Paypal Token')),
            ],
        ),
    ]
