# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

