# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160426_1053'),
    ]

