# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160426_1333'),
    ]

